// Package branding is the single source of truth for the project's
// user-facing brand identity. Anything that's shown to users — UI titles,
// swagger info, log messages, error responses — should reference the
// constants here rather than hard-coding the brand name.
//
// The internal package path (`audiod/internal/...`), binary name (`audiod`),
// env-var prefix (`AUDIOD_*`), cookie name (`audiod_token`), and database
// file (`audiod.db`) are deliberately separate from the brand. Internal
// names exist to identify the running process and persistent state across
// upgrades; renaming them would break every existing deployment. The brand
// is what users see — it can change without touching those.
//
// Rename procedure: change AppName below, run tests, commit. Done.
package branding

// AppName is the user-facing product name. Display it anywhere a user
// might see it: page titles, welcome banners, error messages, swagger
// metadata, marketing copy generated by the server.
const AppName = "Audiotheque"

// AppTagline is the short pitch displayed under the AppName in
// onboarding screens, the README, and OpenAPI metadata.
const AppTagline = "Self-hosted high-resolution music streaming"

// AppDescription is the longer one-paragraph blurb suitable for
// OpenAPI info.description and similar long-form metadata.
const AppDescription = "Audiotheque is a self-hosted music streaming server: " +
	"browse your collection from any browser, sync playback across every " +
	"tab and device in real time, and transfer playback to MPD speakers " +
	"around the house — like a personal Spotify running on your own hardware."
